### ISSUE TITLE
Language ?

### ISSUE THREAD

**Issue by Ardenian** [IDotD/Description-Parser#2]
Is one required to write the parser in a particular language ? 
I could imagine that I could write it in a couple of days using C#, what do you say, @Idrinth ?

From what I understood the parser won't be included somewhere within the script or the website, but be a pseudo-one-time application, so we use it once to get all information from the texts.

**Comment by Idrinth** [comment]
I would prefer something I can run on the server(a debian).Ccalculating the best cases is something I'd rather not do on the fly, so we'd need to keep that updated - meaning there has to be a way to run the parser to update data as well.

**Comment by Ardenian** [comment]
Hm, I see, thank you, well, the actual parsing shouldn't be too much of a problem when it comes to the language, though I might need some consultation regarding the entities and connecting as well as updating the SQL databases.
