### ISSUE TITLE
Raid Type collection ?

### ISSUE THREAD

**Issue by Ardenian** [IDotD/Description-Parser#3]
Is there any existing source for all possible raid types, like Human, Beastman and so on, @Idrinth ? 
Dependent on the actual use and parsing one would need them to filter out raid types from the description.

**Comment by Idrinth** [comment]
[boss-type.sql.txt](https://github.com/IDotD/Description-Parser/files/661232/boss-type.sql.txt)

Just remember you'll need to update those automatically as well

**Comment by Ardenian** [comment]
Do you mean by updating them extracting newly added types to the SQL database 
or adding them to the related magic entity ?

**Comment by Idrinth** [comment]
I mean they change, so you need to get them from the database as well

**Comment by Ardenian** [comment]
Aight, thanks
